remote_theme: chrisrhymes/bulma-clean-theme
title: "Memory in Artificial and Real Intelligence (MemARI)"

defaults:
  -
    scope:
      path: ""
    values:
      hero_image: /img/neworleans.jpeg
      image: /img/logo.jpg
